### ISSUE TITLE
pip install tensorwatch: missing ipywidgets and sklearn

### ISSUE THREAD

**Issue by rfernand2** [microsoft/tensorwatch#1]
After doing "pip install tensorwatch", I tried to run "sum_log.py".  It required me to manually pip install "ipywidgets" and "sklearn" - these should be included tensorwatch's setup.py dependencies.

**Comment by sytelus** [comment]
Thanks for trying this out! I thought those would be included as part of Anaconda distribution. I've added these dependencies and updated PyPi package.

**Comment by rfernand2** [comment]
Cool – thanks!
