### ISSUE TITLE
pip install issue: "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by ophir91** [microsoft/tensorwatch#11]
Hello,
it looks like a very cool tool!!
I tried to install with pip and got the following issue:

Collecting tensorwatch
  Using cached https://files.pythonhosted.org/packages/ce/f2/4885c7f5ddf06224fc1443bb998464755e542c34f9966de4e686b9f1e43e/tensorwatch-0.8.4.tar.gz
Requirement already satisfied: matplotlib in /media/ophir/DATA1/software/anaconda3/envs/pytorch/lib/python3.5/site-packages (from tensorwatch) (2.2.2)
Requirement already satisfied: numpy in /media/ophir/DATA1/software/anaconda3/envs/pytorch/lib/python3.5/site-packages (from tensorwatch) (1.14.2)
Requirement already satisfied: pyzmq in /media/ophir/DATA1/software/anaconda3/envs/pytorch/lib/python3.5/site-packages (from tensorwatch) (17.1.2)
Requirement already satisfied: plotly in /media/ophir/DATA1/software/anaconda3/envs/pytorch/lib/python3.5/site-packages (from tensorwatch) (3.3.0)
Collecting torchstat (from tensorwatch)
  Using cached https://files.pythonhosted.org/packages/bc/fe/f483b907ca80c90f189cd892bb2ce7b2c256010b30314bbec4fc17d1b5f1/torchstat-0.0.7-py3-none-any.whl
Collecting receptivefield (from tensorwatch)
  Using cached https://files.pythonhosted.org/packages/cd/2a/a140221d151e228c5995e34f9c60d1ffd756f8672ccfbce8efe5da780671/receptivefield-0.4.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/media/ophir/DATA1/ilyan/tmp/pip-install-gb2l8gtq/receptivefield/setup.py", line 13
        download_url=f'https://github.com/fornaxai/receptivefield/archive/{VERSION}.tar.gz',
                                                                                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /media/ophir/DATA1/ilyan/tmp/pip-install-gb2l8gtq/receptivefield/

does any one have a solution?

Thanks 
Ophir

**Comment by sytelus** [comment]
This is caused because you are using Python 3.5 and the `receptivefield` package requires Python 3.6. Hope you can upgrade to Python 3.6. Meanwhile, may be we can think about making this dependency optional.

**Comment by sytelus** [comment]
I've removed the offending dependency, for now, so please give it a try and let us know how it goes!

**Comment by ophir91** [comment]
Thanks now it is working,..
