### ISSUE TITLE
Is it really need for pip install -e . for regim

### ISSUE THREAD

**Issue by sakaia** [microsoft/tensorwatch#12]
This is  Jupyter notebook sample issue.
Most of Jupyter notebook sample writes following

```
git clone https://github.com/sytelus/regim.git
cd regim
pip install -e .
```
But I think following 1 line instruction is enough.

```
pip install regim
```

**Comment by sytelus** [comment]
If you want to run mnist training script then you will need to clone the repo. However, otherwise you don't need develop-mode install.
