### ISSUE TITLE
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

### ISSUE THREAD

**Issue by hhaAndroid** [microsoft/tensorwatch#20]
I use the model inside torchvision to work normally. Once I change to my own simple model, I will get the above error.

**Comment by sytelus** [comment]
Could you please post example code that allows us to reproduce the error?

**Comment by hhaAndroid** [comment]
sorry,I found the reason,not a code issue, but onnx does not support

**Comment by yangninghua** [comment]
please tall me
onnx version
