### ISSUE TITLE
Can't generate images

### ISSUE THREAD

**Issue by chl916185** [microsoft/tensorwatch#27]
import tensorwatch as tw
import torchvision.models
alexnet_model = torchvision.models.alexnet()
tw.draw_model(alexnet_model, [1, 3, 224, 224])

error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/anaconda2/envs/pytorch1.0/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda2/envs/pytorch1.0/lib/python3.6/site-packages/tensorwatch/model_graph/hiddenlayer/graph.py in _repr_svg_(self)
    391     def _repr_svg_(self):
    392         """Allows Jupyter notebook to render the graph automatically."""
--> 393         return self.build_dot(self.orientation)._repr_svg_()
    394 
    395     def save(self, path, format="pdf"):

~/anaconda2/envs/pytorch1.0/lib/python3.6/site-packages/tensorwatch/model_graph/hiddenlayer/graph.py in build_dot(self, orientation)
    333         Returns a GraphViz Digraph object.
    334         """
--> 335         from graphviz import Digraph
    336 
    337         # Build GraphViz Digraph

ModuleNotFoundError: No module named 'graphviz'

<tensorwatch.model_graph.hiddenlayer.graph.Graph at 0x7fe7ce046898>

Write it as follows, without error, but without image

import tensorwatch as tw
import torchvision.models
alexnet_model = torchvision.models.alexnet()
dd = tw.draw_model(alexnet_model, [1, 3, 224, 224])
print(dd)

<tensorwatch.model_graph.hiddenlayer.graph.Graph object at 0x7fe7cdfc5c88>

**Comment by coffeedjimmy** [comment]
@chl916185 

Try to install graphviz.

`pip install graphviz`

In addition, I encountered runtime error after executing pip install. 

Please check [this page](https://stackoverflow.com/questions/35064304/runtimeerror-make-sure-the-graphviz-executables-are-on-your-systems-path-aft) to solve that problem.
