### ISSUE TITLE
Provide script files for notebooks?

### ISSUE THREAD

**Issue by awwong1** [microsoft/tensorwatch#4]
Thank you! This project will help a lot of people in their research.

Looking at [notebooks/mnist.ipynb](https://github.com/microsoft/tensorwatch/blob/master/notebooks/mnist.ipynb), how are inputs expected, specifically for the topk visualisations?

I want to understand the block:
```python
rand_pred = train.create_stream(expr="topk_all(l, \
            batch_vals=lambda b: (b.batch.loss_all, (b.batch.input, b.batch.output), b.batch.target), \
            out_f=image_class_outf, order='rnd')", event_name='batch', throttle=2)
```
The tutorials specify using a lambda expression, where `b` contains the watcher observed arguments. I'm not sure how to use `topk_all` and where `l` comes from.

Would it possible to see the training scripts for the notebooks provided in the repository?

**Comment by sytelus** [comment]
Thanks for pointing this out. We will add the script and docs for this notebook and update this issue soon!

**Comment by sytelus** [comment]
We just updated the documentation in tutorials that now has more detail on how to run the training. The `l` in these lambda expressions is supplied internally by TensorWatch. You can basically assume that there is iterator `l` available to you that will provide you the data on each event.

**Comment by awwong1** [comment]
I'm still not sure I follow the latest documentation for the [mnist notebook](https://github.com/microsoft/tensorwatch/blob/master/notebooks/mnist.ipynb).

For the block of code:
```python
rand_pred = train.create_stream(expr="topk_all(l, \
            batch_vals=lambda b: (b.batch.loss_all, (b.batch.input, b.batch.output), b.batch.target), \
            out_f=image_class_outf, order='rnd')", event_name='batch', throttle=2)
```

What is corresponding writer in `mnist_main.py`? I'm looking for something along the lines of this:

```python
import tensorwatch as tw

w = tw.Watcher(filename=args["tensorwatch_log"])
w.observe(
    # tutorial should have arguments, keyword arguments
    # description of types and semantics for each
)
```
