### ISSUE TITLE
Issue with draw model

### ISSUE THREAD

**Issue by mondeg0** [microsoft/tensorwatch#50]
Hello,

I've just installed tensorwatch and try to reproduce the example :
```
import tensorwatch as tw
import torchvision.models

alexnet_model = torchvision.models.alexnet()
tw.draw_model(alexnet_model, [1, 3, 224, 224])
```

and unfortunately I'm gettind the following error : 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/lib/python3.6/site-packages/tensorwatch/model_graph/hiddenlayer/pytorch_draw_model.py in _repr_svg_(self)
     11     def _repr_svg_(self):
     12         """Allows Jupyter notebook to render the graph automatically."""
---> 13         return self.dot._repr_svg_()
     14     def save(self, filename, format="png"):
     15         # self.dot.format = format

AttributeError: 'Dot' object has no attribute '_repr_svg_'
```

My versions are:
- Python 3.6.9
- IPython 7.9.0
- Pytorch 1, 1.2 and 1.3.1 (I have tried with these three versions but nothing changes.) 

I also try to run the given example on google colab and it raises the same error...

Maybe the error comes from my version of IPython ?

**Comment by XYZ0901** [comment]
I have the same err in colab, so how did you solve it

**Comment by mondeg0** [comment]
No, unfortunately I didn't manage to solve the issue... I'm waiting for an answer here =)

**Comment by wangcan1213** [comment]
I got the same error with you, looking for a solution

**Comment by mondeg0** [comment]
@lasp73 has proposed a pull request with a solution, I'm waiting this to be pushed to the master to test again.

**Comment by Sheathluo** [comment]
I have the same error.

**Comment by qiang92** [comment]
I solved this by installing Graphviz2.38 in win10. not conda install graphviz. You need to download the msi file from https://graphviz.gitlab.io/_pages/Download/Download_windows.html and install it. The add its bin path to environment path. 
Then change the pydot.py in your environment. From "self.prog = 'dot'" to "self.prog = 'dot.exe'".

**Comment by Sheathluo** [comment]
Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qiang92"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 中午12:47
收件人:&nbsp;"microsoft/tensorwatch"<tensorwatch@noreply.github.com&gt;;
抄送:&nbsp;"罗韬"<454230747@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/tensorwatch] Issue with draw model (#50)




I solved this by installing Graphviz2.38 in win10. not conda install graphviz. You need to download the msi file from https://graphviz.gitlab.io/_pages/Download/Download_windows.html and install it. The add its bin path to environment path.
 Then change the pydot.py in your environment. From "self.prog = 'dot'" to "self.prog = 'dot.exe'".
