### ISSUE TITLE
Cannot install with pip because depends on package not hosted on PyPi

### ISSUE THREAD

**Issue by jkerfs** [microsoft/tensorwatch#57]
```
> pip install tensorwatch
Collecting tensorwatch
  Using cached tensorwatch-0.9.0.tar.gz (187 kB)
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
tensorwatch depends on pydot@ git+https://github.com/sytelus/pydot@v1.5.0#egg=pydot 
```

However, I can install tensorwatch version 0.8.10 without issue.  I believe the problem was introduced by https://github.com/microsoft/tensorwatch/commit/353567f2071b4c7a5fae5afebeea787523c59762

I'm running ubuntu 16 with pip 20.0.2.

**Comment by yongleex** [comment]
I have the same issue.

**Comment by yaochx** [comment]
Also with the same issue, I've installed pydot with the following
> pip install git+https://github.com/sytelus/pydot@v1.5.0#egg=pydot

**Comment by yaochx** [comment]
> ```
> > pip install tensorwatch
> Collecting tensorwatch
>   Using cached tensorwatch-0.9.0.tar.gz (187 kB)
> ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
> tensorwatch depends on pydot@ git+https://github.com/sytelus/pydot@v1.5.0#egg=pydot 
> ```
> 
> However, I can install tensorwatch version 0.8.10 without issue. I believe the problem was introduced by [353567f](https://github.com/microsoft/tensorwatch/commit/353567f2071b4c7a5fae5afebeea787523c59762)
> 
> I'm running ubuntu 16 with pip 20.0.2.

I installed it with source code

>  python setup.py build
python setup.py install

**Comment by bloodymeli** [comment]
I experience the same issue.

**Comment by jkerfs** [comment]
Seems like @sytelus fixed it with https://github.com/microsoft/tensorwatch/commit/30f770cc97ae399ec4de222c64fb77958704241e.
